# Generated by Django 5.0.6 on 2025-10-03 11:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Unique identifier for the patient', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='patient_images/')),
                ('stage', models.CharField(choices=[('early', 'Early'), ('mid', 'Mid'), ('late', 'Late')], max_length=10)),
                ('vasculitis_present', models.BooleanField(default=False, verbose_name='Vasculitis Present')),
                ('activity', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10, verbose_name='Active/Inactive')),
                ('quality', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Quality (0-10)')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annotations.patient')),
            ],
            options={
                'unique_together': {('patient', 'stage')},
            },
        ),
    ]
