# Generated by Django 5.0.6 on 2025-10-21 01:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('vasculitis_present', models.BooleanField(default=False)),
                ('activity', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('unknown', 'Unknown')], max_length=100, null=True)),
                ('quality', models.IntegerField(blank=True, help_text='Image quality on a scale of 1 (Poor) to 10 (Good)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('is_annotated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('early', 'Early'), ('mid', 'Mid'), ('late', 'Late')], max_length=10)),
                ('image_url', models.URLField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annotations.patient')),
            ],
            options={
                'unique_together': {('patient', 'stage')},
            },
        ),
    ]
