# Generated by Django 5.0.6 on 2025-11-11 07:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_annotated',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='vasculitis_present',
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vasculitis_present', models.BooleanField(default=False)),
                ('activity', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('unknown', 'Unknown')], max_length=100, null=True)),
                ('quality', models.IntegerField(blank=True, help_text='Image quality on a scale of 1 (Poor) to 10 (Good)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('annotated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotations.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'patient')},
            },
        ),
    ]
