# Generated by Django 5.0.6 on 2025-10-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_patient_date_of_birth_patient_date_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
