# Generated by Django 5.0.6 on 2026-02-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_remove_patient_activity_remove_patient_is_annotated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
