# Generated by Django 5.0.6 on 2026-02-04 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_annotation_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patientimage',
            unique_together=set(),
        ),
    ]
