# Generated by Django 5.0.6 on 2026-02-05 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_casecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecomment',
            name='created_at',
        ),
    ]
