# Generated by Django 5.0.6 on 2026-02-05 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_remove_casecomment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
